-- Schema version: v0.1
-- Date: 2026-01-22
-- Owner: TG Bot / Skazka team
-- Creates: users, sessions, session_events, payments, confirm_requests, usage_windows, ui_events + indexes/constraints
-- Note: соответствует DB Schema v0.1 — Field Spec (FINAL)

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tg_id bigint NOT NULL UNIQUE,
  display_name text NOT NULL,
  tg_username text NULL,
  plan text NOT NULL DEFAULT 'FREE',
  plan_started_at timestamptz NULL,
  plan_expires_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tg_id bigint NOT NULL,
  sid8 text NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE',
  theme_id text NULL,
  step int NOT NULL DEFAULT 0,
  max_steps int NOT NULL,
  player_name text NOT NULL,
  params_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  facts_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  memory_summary text NULL,
  ending_id text NULL,
  last_step_message_id bigint NULL,
  last_step_sent_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NULL,
  CONSTRAINT sessions_sid8_unique UNIQUE (sid8),
  CONSTRAINT sessions_tg_id_sid8_unique UNIQUE (tg_id, sid8)
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_status_idx ON sessions (status);
CREATE INDEX IF NOT EXISTS sessions_tg_id_idx ON sessions (tg_id);
CREATE UNIQUE INDEX IF NOT EXISTS sessions_active_user_id_idx
  ON sessions (user_id)
  WHERE status = 'ACTIVE';

CREATE TABLE IF NOT EXISTS session_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  step int NOT NULL,
  user_input text NULL,
  choice_id text NULL,
  llm_json jsonb NULL,
  deltas_json jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT session_events_session_id_step_unique UNIQUE (session_id, step)
);

CREATE INDEX IF NOT EXISTS session_events_session_id_idx ON session_events (session_id);

CREATE TABLE IF NOT EXISTS payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  invoice_id text NOT NULL,
  tx_hash text NULL,
  amount bigint NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'PENDING',
  kind text NOT NULL DEFAULT 'SUB_MONTH',
  period_yyyymm text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT payments_invoice_id_unique UNIQUE (invoice_id)
);

CREATE INDEX IF NOT EXISTS payments_user_id_idx ON payments (user_id);
CREATE INDEX IF NOT EXISTS payments_status_idx ON payments (status);

CREATE TABLE IF NOT EXISTS confirm_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tg_id bigint NOT NULL,
  session_id bigint NULL REFERENCES sessions(id) ON DELETE SET NULL,
  rid8 text NOT NULL,
  kind text NOT NULL,
  payload_json jsonb NULL,
  status text NOT NULL DEFAULT 'PENDING',
  result text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  used_at timestamptz NULL,
  CONSTRAINT confirm_requests_rid8_unique UNIQUE (rid8)
);

CREATE INDEX IF NOT EXISTS confirm_requests_tg_id_idx ON confirm_requests (tg_id);
CREATE INDEX IF NOT EXISTS confirm_requests_user_id_idx ON confirm_requests (user_id);
CREATE INDEX IF NOT EXISTS confirm_requests_expires_at_idx ON confirm_requests (expires_at);
CREATE INDEX IF NOT EXISTS confirm_requests_tg_id_rid8_idx ON confirm_requests (tg_id, rid8);

CREATE TABLE IF NOT EXISTS usage_windows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  window_start timestamptz NOT NULL,
  window_end timestamptz NOT NULL,
  messages_used int NOT NULL DEFAULT 0,
  sessions_started int NOT NULL DEFAULT 0,
  blocked_until timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT usage_windows_user_id_window_start_unique UNIQUE (user_id, window_start)
);

CREATE INDEX IF NOT EXISTS usage_windows_user_id_idx ON usage_windows (user_id);

CREATE TABLE IF NOT EXISTS ui_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  step int NOT NULL,
  kind text NOT NULL,
  content_hash text NOT NULL,
  state text NOT NULL DEFAULT 'PENDING',
  pending_since timestamptz NULL,
  fail_count int NOT NULL DEFAULT 0,
  next_retry_at timestamptz NULL,
  step_message_id bigint NULL,
  recap_message_id bigint NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ui_events_session_step_kind_hash_unique UNIQUE (session_id, step, kind, content_hash)
);

CREATE INDEX IF NOT EXISTS ui_events_session_id_idx ON ui_events (session_id);
CREATE INDEX IF NOT EXISTS ui_events_state_next_retry_at_idx ON ui_events (state, next_retry_at);
