-- TG.3.2.02 — DB v0.2: assets + session_images (no base64 in Postgres)

CREATE TABLE IF NOT EXISTS assets (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind            text        NOT NULL CHECK (kind IN ('image')),
  storage_backend text        NOT NULL CHECK (storage_backend IN ('fs')),
  storage_key     text        NOT NULL CHECK (length(storage_key) > 0),
  mime            text        NOT NULL,
  bytes           bigint      NOT NULL CHECK (bytes > 0),
  sha256          text        NOT NULL CHECK (length(sha256) = 64),
  width           int         NULL CHECK (width IS NULL OR width > 0),
  height          int         NULL CHECK (height IS NULL OR height > 0),
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_assets_sha256 ON assets(sha256);

CREATE TABLE IF NOT EXISTS session_images (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id         bigint      NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  step_ui            int         NOT NULL CHECK (step_ui >= 1),
  asset_id           bigint      NOT NULL REFERENCES assets(id) ON DELETE RESTRICT,
  role               text        NOT NULL CHECK (role IN ('reference','step_image')),
  reference_asset_id bigint      NULL REFERENCES assets(id) ON DELETE RESTRICT,
  image_model        text        NOT NULL,
  prompt             text        NOT NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT ux_session_images_one_per_role UNIQUE (session_id, step_ui, role),
  CONSTRAINT ck_reference_only_step1 CHECK (role <> 'reference' OR step_ui = 1),
  CONSTRAINT ck_reference_has_no_ref CHECK (role <> 'reference' OR reference_asset_id IS NULL)
);

CREATE INDEX IF NOT EXISTS ix_session_images_session_id ON session_images(session_id);
CREATE INDEX IF NOT EXISTS ix_session_images_session_step ON session_images(session_id, step_ui);
