-- TG.2.1.01 + TG.8.2.01
-- child profile snapshot + book jobs + asset kind extension

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS child_name text NULL;

ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS child_name text NULL;

UPDATE sessions s
SET child_name = u.child_name
FROM users u
WHERE s.user_id = u.id
  AND s.child_name IS NULL;

ALTER TABLE assets
  DROP CONSTRAINT IF EXISTS assets_kind_check;

ALTER TABLE assets
  ADD CONSTRAINT assets_kind_check CHECK (kind IN ('image', 'pdf', 'json'));

CREATE TABLE IF NOT EXISTS book_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('book_v1')),
  status text NOT NULL CHECK (status IN ('pending','running','done','error')),
  result_pdf_asset_id bigint NULL REFERENCES assets(id) ON DELETE SET NULL,
  script_json_asset_id bigint NULL REFERENCES assets(id) ON DELETE SET NULL,
  error_message text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ux_book_jobs_session_kind UNIQUE (session_id, kind)
);

CREATE INDEX IF NOT EXISTS ix_book_jobs_session_status ON book_jobs(session_id, status);
